added: xkeysnail-ncaq-daemon: 再起動時にエラー表示させるようにした

diff --git a/xkeysnail-ncaq-daemon b/xkeysnail-ncaq-daemon
--- a/xkeysnail-ncaq-daemon
+++ b/xkeysnail-ncaq-daemon
@@ -1,6 +1,9 @@
 #!/usr/bin/env zsh
 
+set -eux
+
 while
 do
     sudo xkeysnail ~/.xkeysnail-ncaq/config.py
+    >&2 echo "error: xkeysnail rebooted!"
 done
